Repository IBM/beacon-for-ibm-dotcom, pull requests merged in 2021-11, with the labels that each got.

#56 [Beacon] Update CDS messages with follow up steps
  src/audits/carbon-design-system/color-usage-audit.js
  src/audits/carbon-design-system/text-usage-audit.js
Labels: content, design

#61 fix(chrome): add `--disable-setuid-sandbox` flag
  index.js
  package.json
  yarn.lock
Labels: Ready to merge

#62 chore(github): updates to workflows and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-check.yml
  .github/workflows/gh-pages.yml
  .github/workflows/lint.yml
Labels: dev

#64 chore(github): replace with github issue forms and add audit creation
  .github/ISSUE_TEMPLATE/audit_creation.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/contribution_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yaml
  .github/ISSUE_TEMPLATE/user_story.md
  .github/ISSUE_TEMPLATE/user_story.yaml
Labels: Ready to merge
